### ISSUE TITLE
Change to a new Github release version

### ISSUE THREAD

**Issue by lamyergeier** [0x6b/copy-selection-as-markdown#129]
@0x6b 

![image](https://github.com/0x6b/copy-selection-as-markdown/assets/42092626/bc9ea622-f952-433e-a247-500d86bf380b)

**Comment by 0x6b** [comment]
I'm not entirely sure what the issue is, but if you're referring to the Releases section not being updated, here you are: [Release v0.22.0 · 0x6b/copy-selection-as-markdown](https://github.com/0x6b/copy-selection-as-markdown/releases/tag/v0.22.0). If not please reopen the issue with more clear description. Thanks!
