### ISSUE TITLE
Access your data for all websites

### ISSUE THREAD

**Issue by bs** [0x6b/copy-selection-as-markdown#70]
What's the reason this needs access to data for all websites? Couldn't find it anywhere in the documentation!

**Comment by 0x6b** [comment]
Very good question @bs. Since the inception of this addon the `<all_urls>` have exists (almost three years!) but I have to be more careful for this. Will remove unnecessary permissions and release new version.

https://github.com/0x6b/copy-selection-as-markdown/blob/b6e1a4955912fb600f346a8e847ba7cbfa86130c/src/manifest.json#L15-L21

**Comment by 0x6b** [comment]
#72 addressed this issue.

**Comment by 0x6b** [comment]
@bs 0.19.1 with reduced permissions is just released. The extension now doesn't need all website access. Grab the update from your Add-on manager. Thanks again for the issue.
